// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucsezmpencgilipmsvhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjc2V6bXBlbmNnaWxpcG1zdmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjkxNjYsImV4cCI6MjA1OTQ0NTE2Nn0.OyqmHMTH2faT4MAMXFA5tmgY-SLaSTg1ps91AMcXC5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);